services:
  selenium-hub:
    image: selenium/hub:4.25.0-20241024
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.25.0-20241024
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
