services:
  - type: web
    name: selenium-hub
    env: docker
    image: selenium/hub:4.25.0-20241024
    plan: free  # or choose a different plan
    envVars:
      - key: PORT
        value: "4444"  # Ensure this is a string
    ports:
      - "4444"  # This should match the port you're exposing

  - type: web
    name: chrome
    env: docker
    image: selenium/node-chrome:4.25.0-20241024
    plan: free  # or choose a different plan
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: selenium-hub
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
    dependsOn:
      - selenium-hub
